version: "3"

services:
  front:
    image: nikajamburia/mc-maintenance-front
    ports:
      - "80:4200"

  api:
    image: nikajamburia/mc-maintenance-api
    ports:
      - "8080:8000"
    environment:
      PORT: 8000
      DB_CONNECTION_STR: mongodb://database:27015
      DB_NAME: motorcycle_maintenance_schedules

  database:
    image: mongo
    ports:
      - "27015:27017"
    volumes:
      - db_vol:/data/db
    command: mongod --port 27015 --bind_ip 0.0.0.0

  mongoexpress:
    depends_on:
      - database
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_PORT: 27015
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_BASICAUTH_USERNAME: nika
      ME_CONFIG_BASICAUTH_PASSWORD: nika


volumes:
  db_vol: