version: "3"

services:
  api:
    build: .
    ports:
      - "8080:8000"
    environment:
      PORT: 8000
      DB_CONNECTION_STR: mongodb://database:27015
      DB_NAME: motorcycle_maintenance_schedules

  database:
    image: mongo
    ports:
      - "27015:27017"
    volumes:
      - db_vol:/data/db
    command: mongod --port 27015 --bind_ip 0.0.0.0

volumes:
  db_vol: